### ISSUE TITLE
Create base LephareInformer class

### ISSUE THREAD

**Issue by raphaelshirley** [LSSTDESC/rail_lephare#4]
Very basic first stage towards building informer and estimator for rail_lephare as we work through the example goldenspike notebook.

**Comment by sschmidt23** [comment]
There is also a separate RAIL estimation demo notebook that focuses on estimators that might be useful if you are mainly working on implementing an estimator:
https://github.com/LSSTDESC/rail/blob/main/examples/estimation_examples/RAIL_estimation_demo.ipynb

**Comment by raphaelshirley** [comment]
Basic inform class is running in Golden spike notebook. 

We have various changes to implement.
