### ISSUE TITLE
Make redshift grid consistent

### ISSUE THREAD

**Issue by raphaelshirley** [LSSTDESC/rail_lephare#43]
**Bug report**

lephare defines the redshift grid in the config para file. RAIL additionally specifies the grid via stage params. Shall I overwrite the config values so that the grid can be set through RAIL params? Presently rail_lephare is using the values in the config file which could be inconsistent.

@aimalz What do you think?

**Before submitting**
Please check the following:

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [x] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by aimalz** [comment]
Good catch! It would be best for users to specify this kind of thing when creating the stage. That's probably true for everything in the config file; ideally, the config file could be written by the stage to which its parameters are provided so RAIL users could run LePhare without a separate config outside of RAIL stage arguments. Does that make sense?

**Comment by raphaelshirley** [comment]
Yes definitely makes sense I will overwrite the lephare config and think about warning the user.
