### ISSUE TITLE
Example jupyter notebook fails during estimation

### ISSUE THREAD

**Issue by hdante** [LSSTDESC/rail_lephare#48]
Hello, when executing the simple notebook's steps, estimation fails with the following backtrace:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/rail/estimation/estimator.py", line 97, in estimate
    self.run()
  File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/rail/estimation/estimator.py", line 110, in run
    self._process_chunk(s, e, test_data, first)
  File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/rail/estimation/algos/lephare.py", line 208, in _process_chunk
    output, pdfs, zgrid = lp.process(lp.string_dict_to_keymap(self.lephare_config), input, offsets=offsets)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/lephare/process.py", line 91, in process
    output = photz.build_output_tables(photozlist, para_out=None, filename=filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/lephare/_photoz.py", line 38, in build_output_tables
    outkeys = readOutKeywords(self.outpara) if para_out is None else readOutKeywords(para_out)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Incorrect setting for PARA_OUT: can't open output parameter file /lustre/t1/cl/lsst/tmp/henrique.almeida/slurm-home/var/cache/lephare/data/examples/output.para
```

Script was executed line by line in a python REPL shell.

**Before submitting**
Please check the following:

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [x] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by raphaelshirley** [comment]
Hi, thanks for this. We have a quick fix that we will implement in lephare now. If you want to move on you can put the file in place manually getting it from here:

https://github.com/lephare-photoz/lephare-data/blob/main/examples/output.para

**Comment by raphaelshirley** [comment]
you could also run this line to put it in place while we wait for the change to lephare to propagate.

lp.data_retrieval.get_auxiliary_data(keymap=lephare_config, additional_files=["examples/output.para"])

**Comment by raphaelshirley** [comment]
This should have been fixed by https://github.com/lephare-photoz/lephare/pull/146

I'll wait to check this is working as planned after the pypi has updated...

**Comment by hdante** [comment]
Hello, I've repeated the tests using the up-to-date main branches with a clean cache directory, it's working now, thank you.

**Comment by raphaelshirley** [comment]
Great! Thanks again.
